### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by InklessPoet** [Tactical-Combat-Gaming/TCGA3MCL#12]
When you text police it sends the notification in German.
Some shops have the purchase notification in German.
Some shops scroll wheel options are in German.

When you view the wanted list then notification text is German, http://images.akamai.steamusercontent.com/ugc/271715738875919880/88C3D01F84A696C453300E02A91D4E9D5EC48DC8/

The admin menu is in German, http://images.akamai.steamusercontent.com/ugc/271715738875920124/291802C120003A52CE79F0D619294388ABA5ACBE/

The vehicle search notification is in German, http://images.akamai.steamusercontent.com/ugc/271715738875919984/CBF6D9744F03B75C444137398F0E06269C6FD4E3/

In helicopters the tow cable option is in German, http://images.akamai.steamusercontent.com/ugc/271715738875920523/396B8B830B4D5EA63FB692D5413C8A0A05983251/

Cop, EMS, and Civ garages scroll wheel option are in German, http://images.akamai.steamusercontent.com/ugc/271715738875920737/C1694CD0E2F43B3210D6EBAB34498057371C0AC3/

**Comment by TCG-SandMan** [comment]
@InklessPoet we need to know exactly what shops to fix those. Give map coords.

**Comment by InklessPoet** [comment]
http://images.akamai.steamusercontent.com/ugc/271715738879547519/F205BCE2894854868EB1126D803842F8910921BF/

**Comment by InklessPoet** [comment]
Also some mines are still in German. I couldn't check them all so someone will need to check the rest.

http://images.akamai.steamusercontent.com/ugc/271715738879547357/5B5AED8D4358A9421E8A3C22429071C9F67D2246/
http://images.akamai.steamusercontent.com/ugc/271715738879547222/1C48E5E33FFB373ED8872058A0DC681106E5E8D8/
http://images.akamai.steamusercontent.com/ugc/271715738879547071/05328B20CB01DEE3B31CF9586AC4BC289390848D/

**Comment by InklessPoet** [comment]
There also is something that comes up when your gang's karma changes, http://images.akamai.steamusercontent.com/ugc/271715738879546779/35297E37CFBBF63E8CA65591A26EBFB09457C969/

**Comment by InklessPoet** [comment]
Issues has been made to separate tickets.
