### ISSUE TITLE
Mines Scroll Wheel Text

### ISSUE THREAD

**Issue by InklessPoet** [Tactical-Combat-Gaming/TCGA3MCL#38]
Some mines are still in German. I couldn't check them all so someone will need to check the rest.

http://images.akamai.steamusercontent.com/ugc/271715738879547357/5B5AED8D4358A9421E8A3C22429071C9F67D2246/
http://images.akamai.steamusercontent.com/ugc/271715738879547222/1C48E5E33FFB373ED8872058A0DC681106E5E8D8/
http://images.akamai.steamusercontent.com/ugc/271715738879547071/05328B20CB01DEE3B31CF9586AC4BC289390848D/

**Comment by TCG-SandMan** [comment]
Fixed in commit bf7fd86
